Home_Service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("dj-admin/", admin.site.urls),
    path("", include("homeservice.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homeservice/urls.py
from django.urls import path, include
from homeservice import guest_views as views

urlpatterns = [
    path("", views.home, name="home"),
    path("home", views.home, name="home"),
    path("about", views.about, name="about"),
    path("service/", views.service, name="service"),
    path("service/<slug:slug>", views.service_details, name="service_details"),
    path(
        "service/<slug:slug>/<int:employee_id>",
        views.service_details,
        name="service_details",
    ),
    path("career", views.career, name="career"),
    path("contact", views.contact, name="contact"),
    # Authentication
    path("login", views.login_page, name="login"),
    path("signup", views.register_page, name="signup"),
    path("logout", views.logout_user, name="logout"),
    # Customer
    path("customer/", include("homeservice.views.customer.urls")),
    # Employee
    path("employee/", include("homeservice.views.employee.urls")),
    path("complete", views.complete_profile),
    # Admin
    path("admin/", include("homeservice.views.admin.urls")),

    #blog
    path("blog", views.blog, name="blog"),
    path("blog/<slug:slug>", views.blog_post, name="blog_post"),
]

homeservice/views/admin/urls.py
from django.urls import path, include
from . import admin_views as views

app_name = "admin_dashboard"

urlpatterns = [
    path("", views.home, name="admin_home"),
    path("employee/create", views.employee, name="employee_create"),
    path("employee", views.employee_list, name="employee"),
    path("employee/<int:employee_id>/edit", views.employee_edit, name="employee_edit"),
    path("employee/<int:employee_id>/delete", views.employee_delete, name="employee_delete"),
    path(
        "employee/application", views.employee_application, name="employee_application"
    ),
    path(
        "employee/application/<int:employee_id>",
        views.employee_application,
        name="employee_application",
    ),
    path(
        "employee/application/<int:employee_id>/verify",
        views.employee_verification,
        name="employee_verification",
    ),


    # customers
    path("customer", views.customer_list, name="customer"),
    path("customer/<int:customer_id>", views.customer_delete, name="customer_delete"),

    # services
    path("service", views.service_list, name="service"),
    path("service/create", views.service, name="service_create"),
    path("service/<int:service_id>", views.service_delete, name="service_delete"),
    path("service/<int:service_id>/edit", views.service_edit, name="service_edit"),

    # inquiries
    path("inquiry", views.inquiry_list, name="inquiry"),
    path("inquiry/read", views.inquiry_read, name="inquiry_read"),
    path("inquiry/<int:id>/read", views.inquiry_read, name="inquiry_read"),

    # FAQs
    path("faq", views.faq_list, name="faq"),
    path("faq/create", views.faq, name="faq_create"),
    path("faq/<int:faq_id>", views.faq_delete, name="faq_delete"),
    path("faq/<int:faq_id>/edit", views.faq_edit, name="faq_edit"),

    # appointments
    path("appointment", views.appointment_list, name="appointment"),
    path("appointment/<int:id>", views.appointment_list, name="appointment"),

    #blogs
    path("blog/create", views.blog_create, name="blog_create"),
    path("blog/update/<int:id>", views.blog_update, name="blog_update"),

    # applicants: forms submitted from career page
    path("applicant", views.applicant_list, name="applicant"),

    #update profile
    path("profile", views.update_password, name="profile"),
    path("profile_pic", views.update_profile_pic, name="profile_pic"),
]

homeservice/views/customer/urls.py
from django.urls import path
from . import customer_views

app_name = "customer"

urlpatterns = [
    path("", customer_views.home, name="customer_home"),
    path("home", customer_views.home, name="customer_home"),
    path("service/", customer_views.services, name="customer_service"),
    path(
        "service/<slug:slug>",
        customer_views.service_details,
        name="customer_service_details",
    ),
    path("appointment/", customer_views.appointment, name="customer_appointment"),
    path(
        "appointment/<int:service_id>/<int:employee_id>",
        customer_views.appointment,
        name="customer_appointment",
    ),
    path("rating", customer_views.rating, name="rating"),
    path("rating/<int:id>/delete", customer_views.rating_delete, name="rating_delete"),
    path("myappointment", customer_views.myappointment, name="customer_appointments"),
    path("appointment/<int:appointment_id>", customer_views.cancel_appointment, name="cancel_appointment"),
    path("profile", customer_views.customer_profile, name="customer_profile"),
    path("profile_pic", customer_views.update_profile_pic, name="customer_profile_pic"),
    path("logout", customer_views.customer_logout, name="customer_logout"),
]

homeservice/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)

from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.template.defaultfilters import timesince, timeuntil

# from tinymce.models import HTMLField


class CustomUserManager(BaseUserManager):

    def _create_user(
        self, email, fullname, address, phone, password=None, **extra_fields
    ):
        if not email:
            raise ValueError("Email is required")
        if not fullname:
            raise ValueError("Full Name is required")
        if not address:
            raise ValueError("Address is required")
        if not phone:
            raise ValueError("Phone is required")

        email = self.normalize_email(email)
        user = self.model(
            email=email, fullname=fullname, address=address, phone=phone, **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, fullname, address, phone, **extra_fields):
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, fullname, address, phone, **extra_fields)

    def create_superuser(self, email, fullname, address, phone, **extra_fields):
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("role", "admin")
        return self._create_user(email, fullname, address, phone, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=254)
    fullname = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=15)
    profile_pic = models.ImageField(upload_to="profile_pics/", null=True, blank=True)

    ROLE_CHOICES = [
        ("employee", "Employee"),
        ("customer", "Customer"),
        ("admin", "Admin"),
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default="customer")
    is_account_verified = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["fullname", "address", "phone"]

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="service_images/")
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    job_title = models.ForeignKey(Service, on_delete=models.CASCADE)
    experience = models.IntegerField()
    bio = models.TextField()
    previous_work = models.TextField()
    previous_experience = models.TextField()
    is_doc_uploaded = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    ID_TYPE_CHOICES = [
        ("passport", "Passport"),
        ("driving_license", "Driving License"),
        ("national_id", "National ID"),
        # Add more choices as needed
    ]

    id_type = models.CharField(max_length=20, choices=ID_TYPE_CHOICES)

    id_image = models.ImageField(upload_to="Documents/", null=True, blank=True)

    # def add_employee(self, user):
    #     if not user.is_superuser:
    #         self.user = user
    #         self.save()
    #     else:
    #         raise ValueError("You can't add super users as employees")

    def __str__(self):
        return self.user.fullname


class Appointment(models.Model):
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="customer"
    )
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="employee"
    )
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    problem = models.TextField()

    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Approved", "Approved"),
        ("Completed", "Completed"),
        ("Rejected", "Rejected"),
    ]

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Pending")

    def __str__(self):
        return f"{self.customer.fullname} - {self.employee.user.fullname} - {self.service.name}"


class Inquiry(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Rating(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.IntegerField()
    review = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer.fullname + " - " + self.employee.user.fullname


class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()

    def __str__(self):
        return self.question


class Career(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    cv = models.FileField(upload_to="career_cv/")

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = RichTextField()
    created_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def time_since_creation(self):
        delta = timezone.now() - self.created_at
        days = delta.days
        hours, remainder = divmod(delta.seconds, 3600)
        minutes, _ = divmod(remainder, 60)

        if days == 1:
            return "1 day ago"
        elif days > 1 and days < 7:
            return f"{days} days ago"
        elif days >= 7 and days < 30:
            return f"{days // 7} weeks ago"
        elif days >= 30 and days < 365:
            months = days // 30
            remaining_days = days % 30
            if remaining_days == 0:
                return f"{months} months ago"
            return f"{months} months, {remaining_days} days ago"
        else:
            return timesince(self.created_at, timezone.now()) + " ago"

    def time_until_creation(self):
        return timeuntil(self.created_at, timezone.now()) + " from now"

    def __str__(self):
        return self.title

homeservice/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from django.contrib.auth import get_user_model

User = get_user_model()


class MyForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=True,
        validators=[
            RegexValidator(
                regex="^[A-Za-z]+(?:\s[A-Za-z]\.?|(?:\s[A-Za-z]+)+)?$",
                message="First name should contain only alphabetic characters.",
                code="invalid_name",
            ),
        ],
    )

    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already in use.")
        return email

    contact = forms.CharField(
        max_length=15,
        required=True,
        validators=[
            RegexValidator(
                regex="^\+?[0-9]+([-.\s]?[0-9]+)*$",
                message="Phone number should contain only numeric value.",
                code="invalid_name",
            ),
        ],
    )

    def clean_contact(self):
        contact = self.cleaned_data.get("contact")
        if User.objects.filter(phone=contact).exists():
            raise ValidationError("This contact number is already in use.")
        return contact

    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)

    def clean_password(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError("Passwords do not match.")
        return cleaned_data

homeservice/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import MyForm
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages

User = get_user_model()


# Create your views here.
def home(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


def service(request):
    return render(request, "services.html")


def contact(request):
    return render(request, "contact.html")


def login_page(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)
        if user:
            if user.role == "customer":
                login(request, user)
                return HttpResponse("Customer Home")
            elif user.role == "employee":
                login(request, user)
                if not request.user.is_account_verified:
                    # Employee need to verify their account
                    return HttpResponse(
                        "Login Successful, You are a Employee but need to upload your documents"
                    )
                else:
                    return HttpResponse(request, "Login Successful, You are a Employee")
            elif user.role == "admin":
                print("Invalid Email or Password")
                messages.error(request, "Invalid Email or Password")
                print("admin_home")
        else:
            messages.error(request, "Invalid Email or Password")
            redirect("login")
    return render(request, "login.html")


def register_page(request):
    if request.method == "POST":

        name = request.POST["name"]
        email = request.POST["email"]
        address = request.POST["address"]
        contact = request.POST["contact"]
        is_employee = request.POST["is_employee"]
        profile_pic = request.FILES["profile_pic"]
        password = request.POST["password1"]

        form = MyForm(request.POST, request.FILES)

        if form.is_valid():
            if is_employee == "True":
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                    role="employee",
                )
                message = "Employee registered successfully"
                messages.success(request, "Employee registered successfully")
            else:
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                )
                message = "Customer registered successfully"
                messages.success(request, "Customer registered successfully")
            user.set_password(password)
            user.save()
            return redirect("login")
        else:
            return render(request, "register.html", {"form": form})

    return render(request, "register.html")


def logout_user(request):
    logout(request)
    return redirect("login")

homeservice/templates/customer/appointment.html
{% extends 'customer/customer_layout.html' %}
{% load static %}
{% block page_title %}
  Appointment Form
{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}" />
  <style>
    section {
      background: url("{% static 'img/contact.jpeg' %}") no-repeat center center/cover;
    }
    section form {
        background-color: rgb(47 172 255 / 10%);
    }
  </style>
{% endblock %}
{% block main_content %}
  <section name="Appointment">
    <div class="container p-5">
      <div class="row">
        <h2 class="text-center mb-5">Appointment - {{ service.name }}</h2>
          <form action="{% url "customer:customer_appointment" %}" method="post" class="border-5 p-4 px-5 w-50 mx-auto">
            <h2 class="text-center">{{service.name}}</h2>
            {% csrf_token %}
            <input type="hidden" name="service" value="{{service.id}}" />
            <input type="hidden" name="employee" value="{{employee.id}}" />
            <div class="mb-3">
              <label for="Name" class="form-label">Name</label>
              <input type="text" class="form-control" value="{{employee.user.fullname}}" disabled />
            </div>
            <div class="mb-3">
              <label for="phone" class="form-label">Phone</label>
              <input type="text" name="phone" class="form-control" value="{{employee.user.phone}}" disabled />
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email</label>
              <input type="text" class="form-control" value="{{employee.user.email}}" disabled />
            </div>
            <div class="mb-3">
              <label for="date" class="form-label">Time &amp Date</label>
              <input type="datetime-local" name="date_time" class="form-control" required/>
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">What's Your Problem</label>
              <textarea type="text" name="problem" class="form-control" required></textarea>
            </div>
            <div class="submit-button-wrapper d-flex justify-content-end">
              <input type="submit" value="Send" class="submit-btn" />
            </div>
          </form>
      </div>
    </div>
  </section>
{% endblock %}

homeservice/templates/customer/my_appointments.html
{% extends 'customer/customer_layout.html' %}
{% load static %}
{% block page_title %}
  My Appointments
{% endblock %}
{% block links %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}" />
{% endblock %}
{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/message.html' %}
  <section class="ftco-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 text-center mb-4">
          <h2 class="heading-section">My Appointments</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="table-wrap">
            <table class="table table-responsive-xl">
              <thead>
                <tr>
                  <th>Service</th>
                  <th>Service Man</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Contact</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% if appointments %}
                  {% for item in appointments %}
                    <tr class="alert" role="alert">
                      <td>{{ item.service.name }}</td>
                      <td class="d-flex align-items-center">
                        <div class="img" style="background-image: url('{{ item.employee.user.profile_pic.url }}');"></div>
                        <div class="pl-3 name">
                          <span>{{ item.employee.user.fullname }}</span>
                        </div>
                      </td>
                      <td>{{ item.date }}</td>
                      <td>{{ item.time }}</td>
                      <td>{{ item.employee.user.phone }}</td>
                      <td class="status">
                        <span class="
                        {% if item.status == 'Pending' %}
                            {{ 'waiting' }}
                          {% elif item.status == 'Approved' %}
                            {{ 'active' }}
                          {% elif item.status == 'Completed' %}
                            {{ 'completed' }}
                          {% elif item.status == 'Rejected' %}
                            {{ 'rejected' }}
                          {% endif %}
                        ">
                          {{ item.status }}
                        </span>
                      </td>
                      {% if item.status == 'Pending' %}
                        <td class="text-danger fs-6">
                          <a href="{% url 'customer:cancel_appointment' item.id %}" class="text-danger" onclick="return confirm('Are you sure want to cancel appointment ?')"><i class="bi bi-x-lg"></i></a>
                        </td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                {% else %}
                  <tr>
                    <td class="text-center" colspan="5">No Appointments</td>
                  </tr>
                {% endif %}
              </tbody>
            </table>

            {% if view_more %}
              <div class="text-center">
                <a href="" class="btn btn-primary text-center w-25">View More</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

homeservice/templates/customer/service_details.html
{% extends 'customer/customer_layout.html' %}
{% load static %}
{% block page_title %}
  Customer Dashboard
{% endblock %}
{% block main_content %}
  {% include 'components/service_details.html' %}
{% endblock %}

homeservice/templates/customer/services.html
{% extends 'customer/customer_layout.html' %}
{% load static %}
{% block page_title %}
  Services
{% endblock %}
{% block links %}
  <style>
    .Services {
      background-color: #fff;
    }
  </style>
{% endblock %}
{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/services_list.html' %}
{% endblock %}

homeservice/templates/customer/update_profile.html
{% extends 'customer/customer_layout.html' %}
{% load static %}
{% block page_title %}
  My Profile
{% endblock %}
{% block links %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="{% static 'css/profile.css' %}" />

  <style>
    form i {
      position: absolute;
      top: 20px;
      right: -7px;
      /* border: 1px solid; */
      border-radius: 50%;
      /* padding: 11px; */
      height: 30px;
      width: 30px;
      display: flex !important;
      align-items: center;
      justify-content: center;
      background-color: white;
      color: cornflowerblue;
      box-shadow: 0 0 8px 3px #b8b8b8;
    }
  </style>
{% endblock %}
{% block main_content %}
  <section>
    <h2 style="text-align: center" class="mb-5">My Profile</h2>
    <hr />

    <div class="container mt-5">
      <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
          <div class="card h-100">
            <div class="card-body">
              <div class="account-settings">
                <div class="user-profile">
                  <div class="user-avatar">
                    <img class="card-image" src="{{ user.profile_pic.url }}" alt="Maxwell Admin" id="profile_pic_img" />
                    <form enctype="multipart/form-data" method="post" id="profilePictureForm" action="{% url 'customer:customer_profile_pic' %}">
                      {% csrf_token %}
                      <label for="new_pp"><i class="bi bi-pencil-square"></i></label>
                      <input type="file" name="new_pp" id="new_pp" class="d-none" accept="image/png, image/jpg, image/jpeg" />
                      <input type="submit" value="Update Profile" class="btn-sm btn-success mt-3" id="submit-btn" />
                    </form>
                  </div>
                  <h5 class="user-name">{{ user.fullname }}</h5>
                  {% comment %} <h6 class="user-email">{{ user.email }}</h6> {% endcomment %}
                  <h6 class="user-email">{{ user.role|title }}</h6>
                </div>
                {% if request.user.role == 'employee' %}
                  <div class="about">
                    <h5>About</h5>
                    <p>{{ user.bio }}</p>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
          <form action="{% url 'customer:customer_profile' %}" method="post">
            {% csrf_token %}
            <div class="card h-100">
              <div class="card-body">
                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary">Personal Details</h6>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                      <label for="fullName">Full Name</label>
                      <input type="text" class="form-control" id="fullName" placeholder="Enter full name" value="{{ user.fullname }}" disabled />
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                      <label for="eMail">Email</label>
                      <input type="email" class="form-control" id="eMail" placeholder="Enter email ID" value="{{ user.email }}" disabled />
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                      <label for="phone">Phone</label>
                      <input type="text" class="form-control" id="phone" placeholder="Enter phone number" value="{{ user.phone }}" disabled />
                    </div>
                  </div>
                  {% comment %} <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                      <label for="website">Website URL</label>
                      <input type="url" class="form-control" id="website" placeholder="Website url" />
                    </div>
                  </div> {% endcomment %}
                </div>
                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">Password</h6>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                    <div class="form-group">
                      <label for="password">Current Password</label>
                      <input type="password" class="form-control" name="current_password" id="password" placeholder="Enter Current Password" />
                    </div>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                    <div class="form-group">
                      <label for="1">New Password</label>
                      <input type="password" class="form-control" name="new_password" id="password1" placeholder="Enter New Password" />
                    </div>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                    <div class="form-group">
                      <label for="password2">Confirm Password</label>
                      <input type="password" class="form-control" name="confirm_password" id="password2" placeholder="Confirm New Password" />
                      <div class="invalid-feedback" id="password-error">Passwords does not matched.</div>
                    </div>
                  </div>
                </div>
                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                      {% comment %} <button type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</button> {% endcomment %}
                      <input type="submit" id="submit" name="submit" class="btn btn-primary" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block script %}
  <script src="{% static 'js/password_match.js' %}"></script>

  <script>
    let imageInput = document.getElementById('new_pp')
    const img = document.getElementById('profile_pic_img')
    const submit_btn = document.getElementById('submit-btn')
    submit_btn.style = 'display: none;'
    
    imageInput.addEventListener('change', function () {
      const choosedFile = this.files[0]
      if (choosedFile) {
        const reader = new FileReader() //FileReader is a predefined function of JS
        reader.addEventListener('load', function () {
          img.setAttribute('src', reader.result)
          img.style.border = '2px solid red'
          submit_btn.style = 'display: inline;'
        })
        reader.readAsDataURL(choosedFile)
      }
    })
  </script>
{% endblock %}