Home_Service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("dj-admin/", admin.site.urls),
    path("", include("homeservice.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homeservice/urls.py
from django.urls import path, include
from homeservice import guest_views as views

urlpatterns = [
    path("", views.home, name="home"),
    path("home", views.home, name="home"),
    path("about", views.about, name="about"),
    path("service/", views.service, name="service"),
    path("service/<slug:slug>", views.service_details, name="service_details"),
    path(
        "service/<slug:slug>/<int:employee_id>",
        views.service_details,
        name="service_details",
    ),
    path("career", views.career, name="career"),
    path("contact", views.contact, name="contact"),
    # Authentication
    path("login", views.login_page, name="login"),
    path("signup", views.register_page, name="signup"),
    path("logout", views.logout_user, name="logout"),
    # Customer
    path("customer/", include("homeservice.views.customer.urls")),
    # Employee
    path("employee/", include("homeservice.views.employee.urls")),
    path("complete", views.complete_profile),
    # Admin
    path("admin/", include("homeservice.views.admin.urls")),

    #blog
    path("blog", views.blog, name="blog"),
    path("blog/<slug:slug>", views.blog_post, name="blog_post"),
]

homeservice/views/admin/urls.py
from django.urls import path, include
from . import admin_views as views

app_name = "admin_dashboard"

urlpatterns = [
    path("", views.home, name="admin_home"),
    path("employee/create", views.employee, name="employee_create"),
    path("employee", views.employee_list, name="employee"),
    path("employee/<int:employee_id>/edit", views.employee_edit, name="employee_edit"),
    path("employee/<int:employee_id>/delete", views.employee_delete, name="employee_delete"),
    path(
        "employee/application", views.employee_application, name="employee_application"
    ),
    path(
        "employee/application/<int:employee_id>",
        views.employee_application,
        name="employee_application",
    ),
    path(
        "employee/application/<int:employee_id>/verify",
        views.employee_verification,
        name="employee_verification",
    ),


    # customers
    path("customer", views.customer_list, name="customer"),
    path("customer/<int:customer_id>", views.customer_delete, name="customer_delete"),

    # services
    path("service", views.service_list, name="service"),
    path("service/create", views.service, name="service_create"),
    path("service/<int:service_id>", views.service_delete, name="service_delete"),
    path("service/<int:service_id>/edit", views.service_edit, name="service_edit"),

    # inquiries
    path("inquiry", views.inquiry_list, name="inquiry"),
    path("inquiry/read", views.inquiry_read, name="inquiry_read"),
    path("inquiry/<int:id>/read", views.inquiry_read, name="inquiry_read"),

    # FAQs
    path("faq", views.faq_list, name="faq"),
    path("faq/create", views.faq, name="faq_create"),
    path("faq/<int:faq_id>", views.faq_delete, name="faq_delete"),
    path("faq/<int:faq_id>/edit", views.faq_edit, name="faq_edit"),

    # appointments
    path("appointment", views.appointment_list, name="appointment"),
    path("appointment/<int:id>", views.appointment_list, name="appointment"),

    #blogs
    path("blog/create", views.blog_create, name="blog_create"),
    path("blog/update/<int:id>", views.blog_update, name="blog_update"),

    # applicants: forms submitted from career page
    path("applicant", views.applicant_list, name="applicant"),

    #update profile
    path("profile", views.update_password, name="profile"),
    path("profile_pic", views.update_profile_pic, name="profile_pic"),
]

homeservice/views/customer/urls.py
from django.urls import path
from . import customer_views

app_name = "customer"

urlpatterns = [
    path("", customer_views.home, name="customer_home"),
    path("home", customer_views.home, name="customer_home"),
    path("service/", customer_views.services, name="customer_service"),
    path(
        "service/<slug:slug>",
        customer_views.service_details,
        name="customer_service_details",
    ),
    path("appointment/", customer_views.appointment, name="customer_appointment"),
    path(
        "appointment/<int:service_id>/<int:employee_id>",
        customer_views.appointment,
        name="customer_appointment",
    ),
    path("rating", customer_views.rating, name="rating"),
    path("rating/<int:id>/delete", customer_views.rating_delete, name="rating_delete"),
    path("myappointment", customer_views.myappointment, name="customer_appointments"),
    path("appointment/<int:appointment_id>", customer_views.cancel_appointment, name="cancel_appointment"),
    path("profile", customer_views.customer_profile, name="customer_profile"),
    path("profile_pic", customer_views.update_profile_pic, name="customer_profile_pic"),
    path("logout", customer_views.customer_logout, name="customer_logout"),
]

homeservice/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)

from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.template.defaultfilters import timesince, timeuntil

# from tinymce.models import HTMLField


class CustomUserManager(BaseUserManager):

    def _create_user(
        self, email, fullname, address, phone, password=None, **extra_fields
    ):
        if not email:
            raise ValueError("Email is required")
        if not fullname:
            raise ValueError("Full Name is required")
        if not address:
            raise ValueError("Address is required")
        if not phone:
            raise ValueError("Phone is required")

        email = self.normalize_email(email)
        user = self.model(
            email=email, fullname=fullname, address=address, phone=phone, **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, fullname, address, phone, **extra_fields):
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, fullname, address, phone, **extra_fields)

    def create_superuser(self, email, fullname, address, phone, **extra_fields):
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("role", "admin")
        return self._create_user(email, fullname, address, phone, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=254)
    fullname = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=15)
    profile_pic = models.ImageField(upload_to="profile_pics/", null=True, blank=True)

    ROLE_CHOICES = [
        ("employee", "Employee"),
        ("customer", "Customer"),
        ("admin", "Admin"),
    ]
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default="customer")
    is_account_verified = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["fullname", "address", "phone"]

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="service_images/")
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    job_title = models.ForeignKey(Service, on_delete=models.CASCADE)
    experience = models.IntegerField()
    bio = models.TextField()
    previous_work = models.TextField()
    previous_experience = models.TextField()
    is_doc_uploaded = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    ID_TYPE_CHOICES = [
        ("passport", "Passport"),
        ("driving_license", "Driving License"),
        ("national_id", "National ID"),
        # Add more choices as needed
    ]

    id_type = models.CharField(max_length=20, choices=ID_TYPE_CHOICES)

    id_image = models.ImageField(upload_to="Documents/", null=True, blank=True)

    # def add_employee(self, user):
    #     if not user.is_superuser:
    #         self.user = user
    #         self.save()
    #     else:
    #         raise ValueError("You can't add super users as employees")

    def __str__(self):
        return self.user.fullname


class Appointment(models.Model):
    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="customer"
    )
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="employee"
    )
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    problem = models.TextField()

    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Approved", "Approved"),
        ("Completed", "Completed"),
        ("Rejected", "Rejected"),
    ]

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Pending")

    def __str__(self):
        return f"{self.customer.fullname} - {self.employee.user.fullname} - {self.service.name}"


class Inquiry(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Rating(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.IntegerField()
    review = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer.fullname + " - " + self.employee.user.fullname


class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()

    def __str__(self):
        return self.question


class Career(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    cv = models.FileField(upload_to="career_cv/")

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = RichTextField()
    created_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def time_since_creation(self):
        delta = timezone.now() - self.created_at
        days = delta.days
        hours, remainder = divmod(delta.seconds, 3600)
        minutes, _ = divmod(remainder, 60)

        if days == 1:
            return "1 day ago"
        elif days > 1 and days < 7:
            return f"{days} days ago"
        elif days >= 7 and days < 30:
            return f"{days // 7} weeks ago"
        elif days >= 30 and days < 365:
            months = days // 30
            remaining_days = days % 30
            if remaining_days == 0:
                return f"{months} months ago"
            return f"{months} months, {remaining_days} days ago"
        else:
            return timesince(self.created_at, timezone.now()) + " ago"

    def time_until_creation(self):
        return timeuntil(self.created_at, timezone.now()) + " from now"

    def __str__(self):
        return self.title

homeservice/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from django.contrib.auth import get_user_model

User = get_user_model()


class MyForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=True,
        validators=[
            RegexValidator(
                regex="^[A-Za-z]+(?:\s[A-Za-z]\.?|(?:\s[A-Za-z]+)+)?$",
                message="First name should contain only alphabetic characters.",
                code="invalid_name",
            ),
        ],
    )

    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already in use.")
        return email

    contact = forms.CharField(
        max_length=15,
        required=True,
        validators=[
            RegexValidator(
                regex="^\+?[0-9]+([-.\s]?[0-9]+)*$",
                message="Phone number should contain only numeric value.",
                code="invalid_name",
            ),
        ],
    )

    def clean_contact(self):
        contact = self.cleaned_data.get("contact")
        if User.objects.filter(phone=contact).exists():
            raise ValidationError("This contact number is already in use.")
        return contact

    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)

    def clean_password(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError("Passwords do not match.")
        return cleaned_data

homeservice/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import MyForm
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages

User = get_user_model()


# Create your views here.
def home(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


def service(request):
    return render(request, "services.html")


def contact(request):
    return render(request, "contact.html")


def login_page(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)
        if user:
            if user.role == "customer":
                login(request, user)
                return HttpResponse("Customer Home")
            elif user.role == "employee":
                login(request, user)
                if not request.user.is_account_verified:
                    # Employee need to verify their account
                    return HttpResponse(
                        "Login Successful, You are a Employee but need to upload your documents"
                    )
                else:
                    return HttpResponse(request, "Login Successful, You are a Employee")
            elif user.role == "admin":
                print("Invalid Email or Password")
                messages.error(request, "Invalid Email or Password")
                print("admin_home")
        else:
            messages.error(request, "Invalid Email or Password")
            redirect("login")
    return render(request, "login.html")


def register_page(request):
    if request.method == "POST":

        name = request.POST["name"]
        email = request.POST["email"]
        address = request.POST["address"]
        contact = request.POST["contact"]
        is_employee = request.POST["is_employee"]
        profile_pic = request.FILES["profile_pic"]
        password = request.POST["password1"]

        form = MyForm(request.POST, request.FILES)

        if form.is_valid():
            if is_employee == "True":
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                    role="employee",
                )
                message = "Employee registered successfully"
                messages.success(request, "Employee registered successfully")
            else:
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                )
                message = "Customer registered successfully"
                messages.success(request, "Customer registered successfully")
            user.set_password(password)
            user.save()
            return redirect("login")
        else:
            return render(request, "register.html", {"form": form})

    return render(request, "register.html")


def logout_user(request):
    logout(request)
    return redirect("login")

homeservice/templates/about.html
{% extends 'components/layout.html' %}
{% block page_title %}
  About Us
{% endblock %}

{% block main_content %}
  <div class="mt-5"></div>
  <section class="about_section layout_padding-bottom">
    <div class="container">
      <h2 style="text-align: center" class="mb-5">ABOUT US</h2>

      <div class="col-lg-12 col-md-12">
        <div class="img-box">
          <img src="static/img/about-image.jpg" style="height: 500px;" alt="" />
        </div>
      </div>

      <div>
        <h2 style="text-align: center" class="my-5">We are Deco Home - A door to door service for your home</h2>

        <p class="content-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti, facere, temporibus nam doloremque nesciunt recusandae debitis et perspiciatis ratione eveniet soluta repellat expedita aspernatur quisquam sequi voluptate voluptas praesentium quasi id illo minus iure natus modi? Quisquam quidem corporis distinctio esse dolore natus nulla cum omnis dolorem quasi nesciunt molestias nam eveniet laborum ab, veniam enim impedit ullam illo, iusto soluta et quas iste! Deserunt soluta, officiis id ullam nulla aspernatur sapiente ducimus aut impedit molestiae consequatur iure, animi non adipisci dolore iusto omnis consectetur eveniet unde harum minima laudantium nostrum atque quae? Eos libero consequatur aperiam magnam, dolorum excepturi!</p>
      </div>

      <div class="row" id="founder">
        <div class="col-8 col-md-8 col-sm-12 mt-3">
          <div class="section-title">
            <h4 class="section_main_title text-warning"><strong>About Our Founder</strong></h4>
          </div>
          <div class="about-item mt-3">
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nostrum temporibus, unde, consequatur deleniti assumenda aliquid dicta dolorem quaerat, rerum magnam eaque eius cumque accusamus! In impedit eaque ipsa praesentium sunt quam aliquam obcaecati? Praesentium eum commodi provident beatae voluptate ut molestias numquam consequatur voluptatem, totam fuga facilis quae maiores incidunt dolor odio laboriosam cumque repudiandae atque..
              <br />
              <br />
              With best regards
              <br />
              <strong>Mukesh Mahato</strong>
              <br />
              Founder
            </p>
          </div>
        </div>
        <div class="col-4 mt-3 d-flex align-items-center">
          <div class="about-image-box">
            <img src="static/img/founder.jpg" alt="" />
          </div>
        </div>
      </div>

      <div class="goals">
        <div class="sec-title">
          <span class="title">Our Future Goal</span>
          <h2>We want to lead in Home Service</h2>
        </div>
        <div class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Non eius, doloremque odit laborum eaque tenetur accusantium consequuntur cum laboriosam perferendis eligendi culpa a quia nisi, ipsa dolor quam! Tempore, voluptate.</div>

        <div class="sec-title mt-4">
          <h2>Customer Satisfaction</h2>
        </div>
        <div class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Non eius, doloremque odit laborum eaque tenetur accusantium consequuntur cum laboriosam perferendis eligendi culpa a quia nisi, ipsa dolor quam! Tempore, voluptate.</div>
      </div>
    </div>
  </section>
{% endblock %}

homeservice/templates/blog_list.html
{% extends 'components/layout.html' %}
{% block page_title %}
  Blogs
{% endblock %}

{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/message.html' %}
  <section class="layout_padding-bottom">
    <div class="container">
      <h2 style="text-align: center" class="mb-5">Blogs</h2>

      <div class="row">
        <div class="list-group">
          {% if posts %}
            {% for item in posts %}
              <a href="/blog/{{ item.slug }}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ item.title }}</h5>
                  <small>{{ item.time_since_creation }}</small>
                </div>
              </a>
            {% endfor %}
          {% else %}
            <p>No posts found</p>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

homeservice/templates/career.html
{% extends 'components/layout.html' %}
{% block page_title %}
  Career Page
{% endblock %}

{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/message.html' %}
  <section class="contact-section layout_padding-bottom">
    <div class="container">
      <h2 style="text-align: center" class="mb-5">Career Page</h2>
      <div class="row">
        <div class="col-lg-6 col-md-6 d-flex justify-content-centre align-items-center">
          <div class="img-box">
            <img src="static/img/contact.jpeg" alt="" />
          </div>
        </div>
        <div class="col-lg-6 col-md-6 d-flex justify-content-centre align-items-center">
          <div class="detail-box">
            <div class="form">
              <div>
                <div class="contact-form-wrapper d-flex justify-content-center">
                  <form action="{% url 'career' %}" class="contact-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p class="description">Elevate your career with us; send us your CV</p>
                    <div>
                      <input type="text" class="form-control border-white mb-3 form-input" name="name" placeholder="Name" required />
                    </div>
                    <div>
                      <input type="text" class="form-control border-white mb-3 form-input" name="phone" placeholder="Phone" required />
                    </div>
                    <div>
                      <input type="email" class="form-control border-white mb-3 form-input" name="email" placeholder="Email" required />
                    </div>
                    <div>
                      <input type="file" class="form-control" name="cv" accept=".pdf" />
                    </div>
                    <div class="submit-button-wrapper d-flex justify-content-end">
                      <input type="submit" value="Send" class="submit-btn" />
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="blank mt-5 pt-5"></div>
    </div>
  </section>
{% endblock %}

homeservice/templates/contact.html
{% extends 'components/layout.html' %}
{% block page_title %}
  Contact Us
{% endblock %}

{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/message.html' %}
  {% include 'components/contact.html' %}
{% endblock %}

homeservice/templates/login.html
{% extends 'components/layout.html' %}

{% block page_title %}
  Login
{% endblock %}

{% block main_content %}
  <div class="vh-100 d-flex flex-column justify-content-centre align-content-start form-container">
    {% include 'components/message.html' %}
    <main class="form-signin w-40 m-auto p-5 border-5">
      <form action="/login" method="post">
        {% csrf_token %}
        <h1 class="form-title h3 mb-5 fw-normal">Login</h1>

        <div class="form-floating">
          <input type="text" class="form-control" id="Email" name="email" placeholder="Email Address" />
          <label for="Email">Email</label>
        </div>

        <div class="form-floating mt-4">
          <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" />
          <label for="floatingPassword">Password</label>
        </div>
        <button class="btn btn-primary w-100 py-2 mt-4" type="submit">Sign in</button>

        <p class="mt-4 mb-0">
          Not have an account ? <a href="/signup">Create Here</a>
        </p>
      </form>
    </main>
  </div>
{% endblock %}

homeservice/templates/post.html
{% extends 'components/layout.html' %}
{% block page_title %}
  {{ post.title }}
{% endblock %}

{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/message.html' %}
  <section class="layout_padding-bottom">
    <div class="container">
      <h2 style="text-align: center" class="mb-5">{{ post.title }}</h2>
      <div class="row">{{ post.content|safe }}</div>
    </div>̉
  </section>
{% endblock %}

homeservice/templates/service_details.html
{% extends 'components/layout.html' %}
{% load static %}
{% block page_title %}
  Customer Dashboard
{% endblock %}
{% block main_content %}
  {% include 'components/service_details.html' %}
{% endblock %}

homeservice/templates/serviceman.html
{% extends 'components/layout.html' %}
{% load static %}
{% block page_title %}
  Serviceman Profile
{% endblock %}

{% block links %}
  <style>
    .star {
      font-size: 5vh;
      cursor: pointer;
    }
    
    .one {
      color: rgb(255, 0, 0);
    }
    
    .two {
      color: rgb(255, 106, 0);
    }
    
    .three {
      color: rgb(251, 255, 120);
    }
    
    .four {
      color: rgb(255, 255, 0);
    }
    
    .five {
      color: rgb(24, 159, 14);
    }
    .notice_action {
      visibility: hidden;
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
      margin: 0 2rem;
      display: flex;
      justify-content: center;
      align-items: center;
    }
    .notice_action_btns {
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      gap: 1rem;
    }
    
    .card-body:hover .notice_action {
      visibility: visible;
    }
  </style>
{% endblock %}

{% block main_content %}
  {% include 'components/message.html' %}
  <div class="mt-5"></div>
  <section class="layout_padding-bottom">
    <div class="alert fade" role="alert" id="myAlert" style="z-index: 9999;
    position: fixed;
    width: calc(100% - 2rem);
    top: 5rem;
    left: 1rem;
    right: 1rem;"></div>
    <div class="container px-5">
      <h2 style="text-align: center" class="mb-5">Serviceman profile</h2>
      {% comment %} <hr class="p-0 m-0" /> {% endcomment %}
      <div class="row justify-content-center align-items-center">
        <div class="col-lg-4 col-md-4 d-flex justify-content-centre align-items-center">
          <div class="img-box">
            <img src="{{ employee.user.profile_pic.url }}" alt="" />
          </div>
        </div>

        <div class="col-lg-6 col-md-6 d-flex align-items-center">
          <div class="detail-box">
            <h5 class="mb-3">Name: {{ employee.user.fullname }}</h5>
            <h5 class="mb-3">Phone: {{ employee.user.phone }}</h5>
            <h5 class="mb-3">Email: {{ employee.user.email }}</h5>
            <h5 class="mb-3">Experience: {{ employee.experience }} Years</h5>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-8">
          <div class="about mt-5">
            <h2 class="mb-3">About</h2>
            <p>{{ employee.bio }}</p>
          </div>

          <div class="about mt-5">
            <h2 class="mb-3">Previous Work</h2>
            <p>{{ employee.previous_work }}</p>
          </div>
          <div class="about mt-5">
            <h2 class="mb-3">Previous Experience</h2>
            <p>{{ employee.previous_experience }}</p>
          </div>
        </div>
        <div class="col border-5">
          <h3 class="text-center mt-3">Rate Us</h3>
          <form action="{% url 'customer:rating' %}" method="post" id="rating-from">
            {% csrf_token %}
            <div class="stars text-center mb-5">
              <span onclick="gfg(1)" class="star">★</span>
              <span onclick="gfg(2)" class="star">★</span>
              <span onclick="gfg(3)" class="star">★</span>
              <span onclick="gfg(4)" class="star">★</span>
              <span onclick="gfg(5)" class="star">★</span>
              <h3 id="output">Rating is: 0/5</h3>
            </div>
            <div class="form-floating">
              <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px" name="review" required></textarea>
              <label for="floatingTextarea2">How did you like our service?</label>
            </div>

            <input type="hidden" name="rating" id="rating" />
            <input type="hidden" name="employee" value="{{ employee.pk }}" />
            <div class="d-flex justify-content-center my-4">
              <button class="btn btn-primary">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

  <hr class="p-0 m-0" />

  {% include 'components/ratings.html' %}
{% endblock %}

{% block script %}
  <script>
    // To access the stars
    let stars = document.getElementsByClassName('star')
    let output = document.getElementById('output')
    
    // Funtion to update rating
    function gfg(n) {
      remove()
      for (let i = 0; i < n; i++) {
        if (n == 1) cls = 'one'
        else if (n == 2) cls = 'two'
        else if (n == 3) cls = 'three'
        else if (n == 4) cls = 'four'
        else if (n == 5) cls = 'five'
        stars[i].className = 'star ' + cls
      }
      output.innerText = 'Rating is: ' + n + '/5'
    
      document.getElementById('rating').value = n
    }
    
    // To remove the pre-applied styling
    function remove() {
      let i = 0
      while (i < 5) {
        stars[i].className = 'star'
        i++
      }
    }
  </script>
{% endblock %}

homeservice/templates/services.html
{% extends 'components/layout.html' %}
{% block page_title %}
  Services
{% endblock %}

{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/services_list.html' %}
{% endblock %}