Home_Service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("dj-admin/", admin.site.urls),
    path("", include("homeservice.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homeservice/urls.py
from django.urls import path, include
from homeservice import guest_views as views

urlpatterns = [
    path("", views.home, name="home"),
    path("home", views.home, name="home"),
    path("about", views.about, name="about"),
    path("service/", views.service, name="service"),
    path("service/<slug:slug>", views.service_details, name="service_details"),
    path(
        "service/<slug:slug>/<int:employee_id>",
        views.service_details,
        name="service_details",
    ),
    path("career", views.career, name="career"),
    path("contact", views.contact, name="contact"),
    # Authentication
    path("login", views.login_page, name="login"),
    path("signup", views.register_page, name="signup"),
    path("logout", views.logout_user, name="logout"),
    # Customer
    path("customer/", include("homeservice.views.customer.urls")),
    # Employee
    path("employee/", include("homeservice.views.employee.urls")),
    path("complete", views.complete_profile),
    # Admin
    path("admin/", include("homeservice.views.admin.urls")),

    #blog
    path("blog", views.blog, name="blog"),
    path("blog/<slug:slug>", views.blog_post, name="blog_post"),
]

homeservice/views/admin/urls.py
from django.urls import path, include
from . import admin_views as views

app_name = "admin_dashboard"

urlpatterns = [
    path("", views.home, name="admin_home"),
    path("employee/create", views.employee, name="employee_create"),
    path("employee", views.employee_list, name="employee"),
    path("employee/<int:employee_id>/edit", views.employee_edit, name="employee_edit"),
    path("employee/<int:employee_id>/delete", views.employee_delete, name="employee_delete"),
    path(
        "employee/application", views.employee_application, name="employee_application"
    ),
    path(
        "employee/application/<int:employee_id>",
        views.employee_application,
        name="employee_application",
    ),
    path(
        "employee/application/<int:employee_id>/verify",
        views.employee_verification,
        name="employee_verification",
    ),


    # customers
    path("customer", views.customer_list, name="customer"),
    path("customer/<int:customer_id>", views.customer_delete, name="customer_delete"),

    # services
    path("service", views.service_list, name="service"),
    path("service/create", views.service, name="service_create"),
    path("service/<int:service_id>", views.service_delete, name="service_delete"),
    path("service/<int:service_id>/edit", views.service_edit, name="service_edit"),

    # inquiries
    path("inquiry", views.inquiry_list, name="inquiry"),
    path("inquiry/read", views.inquiry_read, name="inquiry_read"),
    path("inquiry/<int:id>/read", views.inquiry_read, name="inquiry_read"),

    # FAQs
    path("faq", views.faq_list, name="faq"),
    path("faq/create", views.faq, name="faq_create"),
    path("faq/<int:faq_id>", views.faq_delete, name="faq_delete"),
    path("faq/<int:faq_id>/edit", views.faq_edit, name="faq_edit"),

    # appointments
    path("appointment", views.appointment_list, name="appointment"),
    path("appointment/<int:id>", views.appointment_list, name="appointment"),

    #blogs
    path("blog/create", views.blog_create, name="blog_create"),
    path("blog/update/<int:id>", views.blog_update, name="blog_update"),

    # applicants: forms submitted from career page
    path("applicant", views.applicant_list, name="applicant"),

    #update profile
    path("profile", views.update_password, name="profile"),
    path("profile_pic", views.update_profile_pic, name="profile_pic"),
]

homeservice/views/customer/urls.py
from django.urls import path
from . import customer_views

app_name = "customer"

urlpatterns = [
    path("", customer_views.home, name="customer_home"),
    path("home", customer_views.home, name="customer_home"),
    path("service/", customer_views.services, name="customer_service"),
    path(
        "service/<slug:slug>",
        customer_views.service_details,
        name="customer_service_details",
    ),
    path("appointment/", customer_views.appointment, name="customer_appointment"),
    path(
        "appointment/<int:service_id>/<int:employee_id>",
        customer_views.appointment,
        name="customer_appointment",
    ),
    path("rating", customer_views.rating, name="rating"),
    path("rating/<int:id>/delete", customer_views.rating_delete, name="rating_delete"),
    path("myappointment", customer_views.myappointment, name="customer_appointments"),
    path("appointment/<int:appointment_id>", customer_views.cancel_appointment, name="cancel_appointment"),
    path("profile", customer_views.customer_profile, name="customer_profile"),
    path("profile_pic", customer_views.update_profile_pic, name="customer_profile_pic"),
    path("logout", customer_views.customer_logout, name="customer_logout"),
]

homeservice/views/employee/urls.py
from django.urls import path
from . import employee_views

app_name = "employee"

urlpatterns = [
    path("register/", employee_views.register, name="employee_register"),
    path("home/", employee_views.home, name="employee_home"),
    path("appointment/", employee_views.appointment, name="employee_appointment"),
    path(
        "appointment/<int:appointment_id>",
        employee_views.appointment,
        name="employee_appointment",
    ),
    path(
        "appointment/<int:appointment_id>/complete",
        employee_views.appointment_completed,
        name="employee_appointment_completed",
    ),
    path("reviews/", employee_views.reviews, name="employee_reviews"),
    path("profile", employee_views.profile, name="employee_profile"),
    path("profile_pic", employee_views.update_profile_pic, name="employee_profile_pic"),
]

homeservice/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from django.contrib.auth import get_user_model

User = get_user_model()


class MyForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=True,
        validators=[
            RegexValidator(
                regex="^[A-Za-z]+(?:\s[A-Za-z]\.?|(?:\s[A-Za-z]+)+)?$",
                message="First name should contain only alphabetic characters.",
                code="invalid_name",
            ),
        ],
    )

    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already in use.")
        return email

    contact = forms.CharField(
        max_length=15,
        required=True,
        validators=[
            RegexValidator(
                regex="^\+?[0-9]+([-.\s]?[0-9]+)*$",
                message="Phone number should contain only numeric value.",
                code="invalid_name",
            ),
        ],
    )

    def clean_contact(self):
        contact = self.cleaned_data.get("contact")
        if User.objects.filter(phone=contact).exists():
            raise ValidationError("This contact number is already in use.")
        return contact

    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)

    def clean_password(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError("Passwords do not match.")
        return cleaned_data

homeservice/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import MyForm
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages

User = get_user_model()


# Create your views here.
def home(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


def service(request):
    return render(request, "services.html")


def contact(request):
    return render(request, "contact.html")


def login_page(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)
        if user:
            if user.role == "customer":
                login(request, user)
                return HttpResponse("Customer Home")
            elif user.role == "employee":
                login(request, user)
                if not request.user.is_account_verified:
                    # Employee need to verify their account
                    return HttpResponse(
                        "Login Successful, You are a Employee but need to upload your documents"
                    )
                else:
                    return HttpResponse(request, "Login Successful, You are a Employee")
            elif user.role == "admin":
                print("Invalid Email or Password")
                messages.error(request, "Invalid Email or Password")
                print("admin_home")
        else:
            messages.error(request, "Invalid Email or Password")
            redirect("login")
    return render(request, "login.html")


def register_page(request):
    if request.method == "POST":

        name = request.POST["name"]
        email = request.POST["email"]
        address = request.POST["address"]
        contact = request.POST["contact"]
        is_employee = request.POST["is_employee"]
        profile_pic = request.FILES["profile_pic"]
        password = request.POST["password1"]

        form = MyForm(request.POST, request.FILES)

        if form.is_valid():
            if is_employee == "True":
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                    role="employee",
                )
                message = "Employee registered successfully"
                messages.success(request, "Employee registered successfully")
            else:
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                )
                message = "Customer registered successfully"
                messages.success(request, "Customer registered successfully")
            user.set_password(password)
            user.save()
            return redirect("login")
        else:
            return render(request, "register.html", {"form": form})

    return render(request, "register.html")


def logout_user(request):
    logout(request)
    return redirect("login")

homeservice/templates/employee/appointments.html
{% extends 'employee/employee_layout.html' %}
{% load static %}
{% block page_title %}
  My Appointments
{% endblock %}
{% block links %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}" />
{% endblock %}
{% block main_content %}
  <div class="mt-5"></div>
  {% include 'components/message.html' %}
  <section class="ftco-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 text-center mb-4">
          <h2 class="heading-section">My Appointments</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="table-wrap">
            <table class="table table-responsive-xl">
              <thead>
                <tr>
                  <th>Customer</th>
                  <th>Problem</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Contact</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% if appointments %}
                  {% for item in appointments %}
                    <tr class="alert" role="alert">
                      <td class="d-flex align-items-center">
                        <div class="img" style="background-image: url('{{ item.customer.profile_pic.url }}');"></div>
                        <div class="pl-3 name">
                          <span>{{ item.customer.fullname }}</span>
                        </div>
                      </td>
                      <td>{{ item.problem }}</td>
                      <td>{{ item.date }}</td>
                      <td>{{ item.time }}</td>
                      <td>{{ item.customer.phone }}</td>
                      <td class="status">
                        <span class="
                        {% if item.status == 'Pending' %}
                            {{ 'waiting' }}
                          {% elif item.status == 'Approved' %}
                            {{ 'active' }}
                          {% elif item.status == 'Completed' %}
                            {{ 'completed' }}
                          {% elif item.status == 'Rejected' %}
                            {{ 'rejected' }}
                          {% endif %}
                        ">
                          {{ item.status }}
                        </span>
                      </td>
                      {% if item.status == 'Pending' %}
                        <td>
                          <a href="{% url 'employee:employee_appointment' item.id %}" class="btn btn-primary">Accept</a>
                        </td>
                      {% endif %}
                      {% if item.status == 'Approved' %}
                        <td>
                          <a href="{% url 'employee:employee_appointment_completed' item.id %}" class="btn btn-primary">Completed</a>
                        </td>
                      {% endif %}
                    </tr>
                  {% endfor %}
                {% else %}
                  <tr>
                    <td class="text-center" colspan="5">No Appointments</td>
                  </tr>
                {% endif %}
              </tbody>
            </table>

            {% if view_more %}
              <div class="text-center">
                <a href="" class="btn btn-primary text-center w-25">View More</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

homeservice/templates/employee/employee_layout.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>
      {% block page_title %}

      {% endblock %}| Home Serevice
    </title>
    <meta name="description" content="Deco Home is a home service platform" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" />
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block links %}

    {% endblock %}
  </head>
  <body>
    {% include 'employee/navbar.html' %}
    <div class="notification" style="z-index: 9999;
    position: fixed;
    width: calc(100% - 2rem);
    top: 5rem;
    left: 1rem;
    right: 1rem;"></div>
    {% include "components/message.html" %}
    {% block main_content %}

    {% endblock %}
    {% include 'components/footer.html' %}

    <script src="{% static 'js/employee_notification.js' %}"></script>
    {% block script %}

    {% endblock %}
  </body>
</html>

homeservice/templates/employee/home.html
{% extends 'employee/employee_layout.html' %}
{% load static %}
{% block page_title %}
  Employee Dashboard
{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}" />
{% endblock %}
{% block main_content %}
  <section class="about_section layout_padding-bottom">
    <div class="container">
      <h2 style="text-align: center" class="my-5">Employee Home Page</h2>
      <hr />

      <div class="col-lg-12 col-md-12">
        <div class="img-box">
          <img src="{% static 'img/customer_home_page.jpg' %}" style="height: ;" alt="" />
        </div>
      </div>
    </div>
  </section>

  <hr class="m-0 p-0" />

  <section class="ftco-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 text-center mb-4">
          <h2 class="heading-section">Recent Bookings</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="table-wrap">
            <table class="table table-responsive-xl">
              <thead>
                <tr>
                  <th>Customer</th>
                  <th>Problem</th>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Contact</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% if appointments %}
                  {% for item in appointments %}
                    <tr class="alert" role="alert">
                      <td class="d-flex align-items-center">
                        <div class="img" style="background-image: url('{{ item.customer.profile_pic.url }}');"></div>
                        <div class="pl-3 name">
                          <span>{{ item.customer.fullname }}</span>
                        </div>
                      </td>
                      <td>{{ item.problem }}</td>
                      <td>{{ item.date }}</td>
                      <td>{{ item.time }}</td>
                      <td>{{ item.customer.phone }}</td>
                      <td class="status">
                        <span class="
                        {% if item.status == 'Pending' %}
                            {{ 'waiting' }}
                          {% elif item.status == 'Accepted' %}
                            {{ 'accepted' }}
                          {% elif item.status == 'Completed' %}
                            {{ 'completed' }}
                          {% elif item.status == 'Rejected' %}
                            {{ 'rejected' }}
                          {% endif %}
                        ">
                          {{ item.status }}
                        </span>
                      </td>
                      <td>
                        <a href="{% url 'employee:employee_appointment' item.id %}" class="btn btn-primary">Accept</a>
                      </td>
                    </tr>
                  {% endfor %}
                {% else %}
                  <tr>
                    <td class="text-center" colspan="8">No Pending Appointments</td>
                  </tr>
                {% endif %}
              </tbody>
            </table>

            {% if view_more %}
              <div class="text-center">
                <a href="" class="btn btn-primary text-center w-25">View More</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

homeservice/templates/employee/navbar.html
<div class="nav-wrapper position-fixed w-100 top-0">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        Home Serevice
        <!-- <img src="icons/logo.png" style="height: 40px" /> -->
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a href="/employee/home" class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'employee:employee_reviews' %}" class="nav-link">Reviews</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'employee:employee_appointment' %}">My Appointment</a>
          </li>
        </ul>
        <li class="nav-item dropdown" style="list-style-type: none;">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="role d-inline">
              <div class="profile-pic">
                <img src="{{ user.profile_pic.url }}" alt="Profile Picture" />
              </div>
              <span>{{ user.fullname }}</span>
              <span style="position: absolute;">{{ user.role }}</span>
            </div>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'employee:employee_profile' %}"><i class="bi bi-person"></i> My Profile</a>
            </li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="/logout"><i class="bi bi-box-arrow-right"></i> Log Out</a>
              <input type="hidden" id="employeeID" value="{{ user.pk }}" />
            </li>
          </ul>
        </li>
      </div>
    </div>
  </nav>
</div>

homeservice/templates/employee/profile.html
{% extends 'employee/employee_layout.html' %}
{% load static %}
{% block page_title %}
  My Profile
{% endblock %}
{% block links %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="{% static 'css/profile.css' %}" />

  <style>
    form i {
      position: absolute;
      top: 20px;
      right: -7px;
      /* border: 1px solid; */
      border-radius: 50%;
      /* padding: 11px; */
      height: 30px;
      width: 30px;
      display: flex !important;
      align-items: center;
      justify-content: center;
      background-color: white;
      color: cornflowerblue;
      box-shadow: 0 0 8px 3px #b8b8b8;
    }
  </style>
{% endblock %}
{% block main_content %}
  <section>
    <h2 style="text-align: center" class="mb-5">My Profile</h2>
    <hr />

    <div class="container mt-5">
      <div class="row gutters">
        <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
          <div class="card h-100">
            <div class="card-body">
              <div class="account-settings">
                <div class="user-profile">
                  <div class="user-avatar">
                    <img class="card-image" src="{{ user.profile_pic.url }}" alt="Maxwell Admin" id="profile_pic_img" />
                    <form enctype="multipart/form-data" method="post" id="profilePictureForm" action="{% url 'employee:employee_profile_pic' %}">
                      {% csrf_token %}
                      <label for="new_pp"><i class="bi bi-pencil-square"></i></label>
                      <input type="file" name="new_pp" id="new_pp" class="d-none" accept="image/png, image/jpg, image/jpeg" />
                      <input type="submit" value="Update Profile" class="btn-sm btn-success mt-3" id="submit-btn" />
                    </form>
                  </div>
                  <h5 class="user-name">{{ user.fullname }}</h5>
                  {% comment %} <h6 class="user-email">{{ user.email }}</h6> {% endcomment %}
                  <h6 class="user-email">{{ user.role|title }}</h6>
                </div>
                {% if request.user.role == 'employee' %}
                  <div class="about">
                    <h5>About</h5>
                    <p>{{ employee.bio }}</p>
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
          <div class="card h-100">
            <div class="card-body">
              <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                  <h6 class="mb-2 text-primary">Personal Details</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                  <div class="form-group">
                    <label for="fullName">Full Name</label>
                    <input type="text" class="form-control" id="fullName" placeholder="Enter full name" value="{{ user.fullname }}" disabled />
                  </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                  <div class="form-group">
                    <label for="eMail">Email</label>
                    <input type="email" class="form-control" id="eMail" placeholder="Enter email ID" value="{{ user.email }}" disabled />
                  </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                  <div class="form-group">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" placeholder="Enter phone number" value="{{ user.phone }}" disabled />
                  </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                  <div class="form-group">
                    <label>Service Title</label>
                    <input type="text" class="form-control" value="{{ employee.job_title }}" disabled />
                  </div>
                </div>
                {% comment %} <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                  <div class="form-group">
                    <label for="website">Website URL</label>
                    <input type="url" class="form-control" id="website" placeholder="Website url" />
                  </div>
                </div> {% endcomment %}
              </div>
              <form action="{% url 'employee:employee_profile' %}" method="post">
                {% csrf_token %}
                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">Password</h6>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                    <div class="form-group">
                      <label for="password">Current Password</label>
                      <input type="password" class="form-control" name="current_password" id="password" placeholder="Enter Current Password" required />
                    </div>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                    <div class="form-group">
                      <label for="1">New Password</label>
                      <input type="password" class="form-control" name="new_password" id="password1" placeholder="Enter New Password" required />
                    </div>
                  </div>
                  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-12">
                    <div class="form-group">
                      <label for="password2">Confirm Password</label>
                      <input type="password" class="form-control" name="confirm_password" id="password2" placeholder="Confirm New Password" required />
                      <div class="invalid-feedback" id="password-error">Passwords does not matched.</div>
                    </div>
                  </div>
                </div>
                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                      <input type="submit" name="update_password" value="Update Password" class="btn btn-primary" />
                    </div>
                  </div>
                </div>
              </form>
              <form action="{% url 'employee:employee_profile' %}" method="post">
                {% csrf_token %}
                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">About</h6>
                  </div>
                  <div class="col">
                    <div class="form-group">
                      <label for="about">About</label>
                      <textarea type="text" class="form-control" id="about" name="bio" rows="5" placeholder="Descrive your previous work" required>{{ employee.bio }}</textarea>
                    </div>
                  </div>
                </div>

                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mt-3 mb-2 text-primary">Work &amp; Experience</h6>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                      <label for="previous_work">Previous Work</label>
                      <textarea type="text" class="form-control" id="previous_work" rows="5" placeholder="Descrive your previous work" name="previous_work" required>{{ employee.previous_work }}</textarea>
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                      <label for="previous_experience">Experience</label>
                      <textarea type="text" class="form-control" id="previous_experience" rows="5" placeholder="Write your previous_experience" name="previous_experience" required>{{ employee.previous_experience }}</textarea>
                    </div>
                  </div>
                </div>

                <div class="row gutters">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                      <input type="submit" name="update_profile" value="Update Profile" class="btn btn-primary" />
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block script %}
  <script src="{% static 'js/password_match.js' %}"></script>
  <script>
    let imageInput = document.getElementById('new_pp')
    const img = document.getElementById('profile_pic_img')
    const submit_btn = document.getElementById('submit-btn')
    submit_btn.style = 'display: none;'
    
    imageInput.addEventListener('change', function () {
      const choosedFile = this.files[0]
      if (choosedFile) {
        const reader = new FileReader() //FileReader is a predefined function of JS
        reader.addEventListener('load', function () {
          img.setAttribute('src', reader.result)
          img.style.border = '2px solid red'
          submit_btn.style = 'display: inline;'
        })
        reader.readAsDataURL(choosedFile)
      }
    })
  </script>
{% endblock %}