Home_Service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("dj-admin/", admin.site.urls),
    path("", include("homeservice.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homeservice/urls.py
from django.urls import path, include
from homeservice import guest_views as views

urlpatterns = [
    path("", views.home, name="home"),
    path("home", views.home, name="home"),
    path("about", views.about, name="about"),
    path("service/", views.service, name="service"),
    path("service/<slug:slug>", views.service_details, name="service_details"),
    path(
        "service/<slug:slug>/<int:employee_id>",
        views.service_details,
        name="service_details",
    ),
    path("career", views.career, name="career"),
    path("contact", views.contact, name="contact"),
    # Authentication
    path("login", views.login_page, name="login"),
    path("signup", views.register_page, name="signup"),
    path("logout", views.logout_user, name="logout"),
    # Customer
    path("customer/", include("homeservice.views.customer.urls")),
    # Employee
    path("employee/", include("homeservice.views.employee.urls")),
    path("complete", views.complete_profile),
    # Admin
    path("admin/", include("homeservice.views.admin.urls")),

    #blog
    path("blog", views.blog, name="blog"),
    path("blog/<slug:slug>", views.blog_post, name="blog_post"),
]

homeservice/views/admin/urls.py
from django.urls import path, include
from . import admin_views as views

app_name = "admin_dashboard"

urlpatterns = [
    path("", views.home, name="admin_home"),
    path("employee/create", views.employee, name="employee_create"),
    path("employee", views.employee_list, name="employee"),
    path("employee/<int:employee_id>/edit", views.employee_edit, name="employee_edit"),
    path("employee/<int:employee_id>/delete", views.employee_delete, name="employee_delete"),
    path(
        "employee/application", views.employee_application, name="employee_application"
    ),
    path(
        "employee/application/<int:employee_id>",
        views.employee_application,
        name="employee_application",
    ),
    path(
        "employee/application/<int:employee_id>/verify",
        views.employee_verification,
        name="employee_verification",
    ),


    # customers
    path("customer", views.customer_list, name="customer"),
    path("customer/<int:customer_id>", views.customer_delete, name="customer_delete"),

    # services
    path("service", views.service_list, name="service"),
    path("service/create", views.service, name="service_create"),
    path("service/<int:service_id>", views.service_delete, name="service_delete"),
    path("service/<int:service_id>/edit", views.service_edit, name="service_edit"),

    # inquiries
    path("inquiry", views.inquiry_list, name="inquiry"),
    path("inquiry/read", views.inquiry_read, name="inquiry_read"),
    path("inquiry/<int:id>/read", views.inquiry_read, name="inquiry_read"),

    # FAQs
    path("faq", views.faq_list, name="faq"),
    path("faq/create", views.faq, name="faq_create"),
    path("faq/<int:faq_id>", views.faq_delete, name="faq_delete"),
    path("faq/<int:faq_id>/edit", views.faq_edit, name="faq_edit"),

    # appointments
    path("appointment", views.appointment_list, name="appointment"),
    path("appointment/<int:id>", views.appointment_list, name="appointment"),

    #blogs
    path("blog/create", views.blog_create, name="blog_create"),
    path("blog/update/<int:id>", views.blog_update, name="blog_update"),

    # applicants: forms submitted from career page
    path("applicant", views.applicant_list, name="applicant"),

    #update profile
    path("profile", views.update_password, name="profile"),
    path("profile_pic", views.update_profile_pic, name="profile_pic"),
]

homeservice/views/customer/urls.py
from django.urls import path
from . import customer_views

app_name = "customer"

urlpatterns = [
    path("", customer_views.home, name="customer_home"),
    path("home", customer_views.home, name="customer_home"),
    path("service/", customer_views.services, name="customer_service"),
    path(
        "service/<slug:slug>",
        customer_views.service_details,
        name="customer_service_details",
    ),
    path("appointment/", customer_views.appointment, name="customer_appointment"),
    path(
        "appointment/<int:service_id>/<int:employee_id>",
        customer_views.appointment,
        name="customer_appointment",
    ),
    path("rating", customer_views.rating, name="rating"),
    path("rating/<int:id>/delete", customer_views.rating_delete, name="rating_delete"),
    path("myappointment", customer_views.myappointment, name="customer_appointments"),
    path("appointment/<int:appointment_id>", customer_views.cancel_appointment, name="cancel_appointment"),
    path("profile", customer_views.customer_profile, name="customer_profile"),
    path("profile_pic", customer_views.update_profile_pic, name="customer_profile_pic"),
    path("logout", customer_views.customer_logout, name="customer_logout"),
]

homeservice/views/employee/urls.py
from django.urls import path
from . import employee_views

app_name = "employee"

urlpatterns = [
    path("register/", employee_views.register, name="employee_register"),
    path("home/", employee_views.home, name="employee_home"),
    path("appointment/", employee_views.appointment, name="employee_appointment"),
    path(
        "appointment/<int:appointment_id>",
        employee_views.appointment,
        name="employee_appointment",
    ),
    path(
        "appointment/<int:appointment_id>/complete",
        employee_views.appointment_completed,
        name="employee_appointment_completed",
    ),
    path("reviews/", employee_views.reviews, name="employee_reviews"),
    path("profile", employee_views.profile, name="employee_profile"),
    path("profile_pic", employee_views.update_profile_pic, name="employee_profile_pic"),
]

homeservice/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from django.contrib.auth import get_user_model

User = get_user_model()


class MyForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        required=True,
        validators=[
            RegexValidator(
                regex="^[A-Za-z]+(?:\s[A-Za-z]\.?|(?:\s[A-Za-z]+)+)?$",
                message="First name should contain only alphabetic characters.",
                code="invalid_name",
            ),
        ],
    )

    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already in use.")
        return email

    contact = forms.CharField(
        max_length=15,
        required=True,
        validators=[
            RegexValidator(
                regex="^\+?[0-9]+([-.\s]?[0-9]+)*$",
                message="Phone number should contain only numeric value.",
                code="invalid_name",
            ),
        ],
    )

    def clean_contact(self):
        contact = self.cleaned_data.get("contact")
        if User.objects.filter(phone=contact).exists():
            raise ValidationError("This contact number is already in use.")
        return contact

    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)

    def clean_password(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError("Passwords do not match.")
        return cleaned_data

homeservice/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import MyForm
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages

User = get_user_model()


# Create your views here.
def home(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


def service(request):
    return render(request, "services.html")


def contact(request):
    return render(request, "contact.html")


def login_page(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = authenticate(email=email, password=password)
        if user:
            if user.role == "customer":
                login(request, user)
                return HttpResponse("Customer Home")
            elif user.role == "employee":
                login(request, user)
                if not request.user.is_account_verified:
                    # Employee need to verify their account
                    return HttpResponse(
                        "Login Successful, You are a Employee but need to upload your documents"
                    )
                else:
                    return HttpResponse(request, "Login Successful, You are a Employee")
            elif user.role == "admin":
                print("Invalid Email or Password")
                messages.error(request, "Invalid Email or Password")
                print("admin_home")
        else:
            messages.error(request, "Invalid Email or Password")
            redirect("login")
    return render(request, "login.html")


def register_page(request):
    if request.method == "POST":

        name = request.POST["name"]
        email = request.POST["email"]
        address = request.POST["address"]
        contact = request.POST["contact"]
        is_employee = request.POST["is_employee"]
        profile_pic = request.FILES["profile_pic"]
        password = request.POST["password1"]

        form = MyForm(request.POST, request.FILES)

        if form.is_valid():
            if is_employee == "True":
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                    role="employee",
                )
                message = "Employee registered successfully"
                messages.success(request, "Employee registered successfully")
            else:
                user = User.objects.create_user(
                    email=email,
                    fullname=name,
                    address=address,
                    phone=contact,
                    profile_pic=profile_pic,
                )
                message = "Customer registered successfully"
                messages.success(request, "Customer registered successfully")
            user.set_password(password)
            user.save()
            return redirect("login")
        else:
            return render(request, "register.html", {"form": form})

    return render(request, "register.html")


def logout_user(request):
    logout(request)
    return redirect("login")

homeservice/templates/components/about.html
<section class="about_section layout_padding-bottom">
  <div class="container">
    <h2 style="text-align: center" class="mb-5">ABOUT US</h2>
    <div class="row">
      <div class="col-lg-6 col-md-6 d-flex justify-content-centre align-items-center">
        <div class="detail-box">
          <h2>Take A Look About Our Companny</h2>
          <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomisedThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised</p>
          <a href="/about">Read More</a>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="img-box">
          <img src="static/img/about-image.jpg" alt="" />
        </div>
      </div>
    </div>

    <div class="blank mt-5 pt-5"></div>

    <div class="row">
      <h1>Why Choose Us</h1>

      <div class="lists">
        <ul>
          <li>Affordablity</li>
          <li>Affordablity</li>
          <li>Affordablity</li>
          <li>Affordablity</li>
          <li>Affordablity</li>
        </ul>
      </div>
    </div>
  </div>
</section>

homeservice/templates/components/contact.html
<section class="contact-section layout_padding-bottom">
  <div class="container">
    <h2 style="text-align: center" class="mb-5">Contact US</h2>
    <div class="row">
      <div class="col-lg-6 col-md-6 d-flex justify-content-centre align-items-center">
        <div class="img-box">
          <img src="static/img/contact.jpeg" alt="" />
        </div>
      </div>
      <div class="col-lg-6 col-md-6 d-flex justify-content-centre align-items-center">
        <div class="detail-box">
          <div class="form">
            <div>
              <div class="contact-form-wrapper d-flex justify-content-center">
                <form action="{% url "contact" %}" class="contact-form" method="post">
                  {% csrf_token %}
                  <p class="description">Feel free to contact us if you need any assistance, any help or another question.</p>
                  <div>
                    <input type="text" class="form-control border-white mb-3 form-input" name="name" placeholder="Name" required />
                  </div>
                  <div>
                    <input type="text" class="form-control border-white mb-3 form-input" name="phone" placeholder="Phone" required />
                  </div>
                  <div>
                    <input type="email" class="form-control border-white mb-3 form-input" name="email" placeholder="Email" required />
                  </div>
                  <div>
                    <textarea id="message" class="form-control border-white mb-3 form-text-area" name="message" rows="5" cols="30" placeholder="Message" required></textarea>
                  </div>
                  <div class="submit-button-wrapper d-flex justify-content-end">
                    <input type="submit" value="Send" class="submit-btn" />
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="blank mt-5 pt-5"></div>
  </div>
</section>

homeservice/templates/components/footer.html
<hr class="m-0 p-0" />
<footer>
  <div class="contact-section pt-5 pb-5 d-flex">
    <div class="col-xl-4 col-md-4 text-center">
      <span class="text-black" style="font-size:23px ; ">&nbsp;Office Address:</span>
      <br />
      <span>Naya Basti, Banepa-09, Kavreplanchowk, Bagmati, Nepal</span>
    </div>

    <div class="col-xl-4 col-md-4 text-center">
      <span class="text-black" style="font-size:23px ;">&nbsp;Contact No:</span><br />
      <span>
        Phone: 9812345678
        <br />
        Whatsapp: 9812345678
      </span>
      <br />
    </div>

    <div class="col-xl-4 col-md-4 text-center">
      <a target="_blank" style="text-decoration: none;" href="mailto:info@decohome.com">
        <span class="text-black" style="font-size:23px ;">&nbsp;Mailus:</span>
        <br />
        <span>info@decohome.com</span>
      </a>
    </div>
  </div>

  <hr class="p-0 m-0" />

  <div class="copyright-area p-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-6 text-center text-lg-left">
          <div class="copyright-text text-justify">
            <p class="p-0 m-0">Copyright © 2024, All Right reserved by Home Serevice</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" async defer></script>

homeservice/templates/components/layout.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>
      {% block page_title %}

      {% endblock %}| Home Serevice
    </title>
    <meta name="description" content="Deco Home is a home service platform" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" />
    <link rel="shortcut icon" href="static/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% block links %}

    {% endblock %}
  </head>
  <body>
    {% include 'components/navbar.html' %}
    {% block main_content %}

    {% endblock %}
    {% include 'components/footer.html' %}

    {% block script %}

    {% endblock %}
  </body>
</html>

homeservice/templates/components/message.html
{% if messages %}
  {% for message in messages %}
    <div id="alert_msg" class="alert {{ message.tags }} alert-dismissible fade show" role="alert" style="z-index: 9999;
    position: fixed;
    width: calc(100% - 2rem);
    top: 5rem;
    left: 1rem;
    right: 1rem;">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}

{% block script %}
  <script>
    setTimeout(function () {
      document.getElementById('alert_msg').remove()
    }, 5000)
  </script>
{% endblock %}

homeservice/templates/components/navbar.html
<div class="nav-wrapper position-fixed w-100 top-0">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        Home Serevice
        <!-- <img src="icons/logo.png" style="height: 40px" /> -->
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% if user.is_authenticated and user.role == 'customer' %}
              <a href="{% url 'customer:customer_home' %}" class="nav-link">Home</a>
            {% elif user.is_authenticated and user.role == 'employee' %}
              <a href="{% url 'employee:employee_home' %}" class="nav-link">Home</a>
            {% else %}
              <a href="{% url 'home' %}" class="nav-link">Home</a>
            {% endif %}
          </li>
          <li>
            <a class="nav-link" href="/about">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/service">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}#faq_section">FAQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/career">Career</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog">Blog</a>
          </li>
        </ul>

        <form class="d-flex me-3" role="search" action="{% url 'service' %}">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" />
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        {% if request.user.is_anonymous %}
          <a href="/signup" class="btn btn-outline-primary">Sign Up</a>
        {% else %}
          <li class="nav-item dropdown" style="list-style-type: none;">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="role d-inline">
                <div class="profile-pic">
                  <img src="{{ user.profile_pic.url }}" alt="Profile Picture" />
                </div>
                <span>{{ user.fullname }}</span>
                <span style="position: absolute;">{{ user.role }}</span>
              </div>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                {% if request.user.role == 'employee' %}
                  <a class="dropdown-item" href="{% url 'employee:employee_profile' %}"><i class="bi bi-person"></i> My Profile</a>
                {% else %}
                  <a class="dropdown-item" href="{% url 'customer:customer_profile' %}"><i class="bi bi-person"></i> My Profile</a>
                {% endif %}
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a class="dropdown-item" href="/logout"><i class="bi bi-box-arrow-right"></i> Log Out</a>
              </li>
            </ul>
          </li>
        {% endif %}
      </div>
    </div>
  </nav>
</div>

homeservice/templates/components/ratings.html
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="mb-5 text-center">Rating &amp; Reviews</h2>
      </div>
    </div>
    {% if reviews %}
      {% for review in reviews %}
        <div class="row d-flex justify-content-center mb-3">
          <div class="col">
            <div class="card border-bottom" style="border: 0">
              <div class="card-body p-0">
                <div class="row">
                  <div class="col-lg-4 d-flex justify-content-center align-items-center mb-4 mb-lg-0">
                    <img src="{{ review.customer.profile_pic.url }}" class="rounded-circle shadow-1" alt="woman avatar" width="150" height="150" style="object-fit: cover;" />
                  </div>
                  <div class="col-lg-8">
                    <ul class="list-unstyled d-flex" style="font-size: 1.5rem;">
                      {% for i in review.rate %}
                        <li class="me-2">
                          <i class="bi bi-star-fill text-warning"></i>
                        </li>
                      {% endfor %}
                    </ul>
                    <p class="text-muted fw-light">{{ review.review }}</p>
                    <p class="fw-bold lead mb-2">
                      <strong>{{ review.customer.fullname }}</strong>
                    </p>
                    <p class="text-muted fw-light text-end">
                      Posted on: <i>{{ review.date }}</i>
                    </p>

                    {% if review.customer == request.user %}
                      <div class="notice_action">
                        <div class="notice_action_btns">
                          <a class="btn btn-danger w-100" href="/customer/rating/{{review.pk}}/delete" onclick="return confirm('Are you sure want to delete ?')">Delete</a>
                        </div>
                      </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>No Reviews for the serviceman.</p>
    {% endif %}
  </div>
</section>

homeservice/templates/components/service_details.html
<section>
  <div class="content-header" id="contact">
    <h1 class="text-dark my-5" style="text-align: center">{{ service.name }}</h1>
  </div>
  <div class="container">
    <div class="row">
      {% comment %}banner image{% endcomment %}
      <div class="col-lg-12 mt-3">
        <div class="col-lg-12 col-md-12 mb-5">
          <div class="img-box">
            <img src="{{ service.image.url }}" style="height: 500px;" alt="" />
          </div>
        </div>
        <h1 style="color: rgb(8, 8, 236);">Introduction</h1>
        <div class="about-item mt-3">
          <p>{{ service.description }}</p>
        </div>
      </div>

      <div class="section-title mt-5">
        <h1 class="section_main_title text-black text-center mb-5">Our Service Provider</h1>
      </div>

      {% comment %}service providers profile card{% endcomment %}
      <div class="about-item">
        <div class="row justify-content-center">
          {% if employees %}
            {% for employee in employees %}
              <div class="col-4 d-flex justify-content-center my-3" style="width: 18rem;">
                <div class="card align-items-center" style="width: 18rem;">
                  <img src="{{ employee.user.profile_pic.url }}" class="card-img-top card-image employee-img" alt="{{ employee.user.fullname }}" />
                  <div class="card-body">
                    <h5 class="card-title">{{ employee.user.fullname }}</h5>
                    {% comment %} <span class="service-provider-post d-block">Plumber</span> {% endcomment %}
                    <span>Experience:</span> <b>{{ employee.experience }} Years</b>
                    <p class="contact mt-2 mb-0">{{ employee.user.phone }}</p>
                    <p class="email mt-2">{{ employee.user.email }}</p>
                    {% comment %} <a href="mailto:{{ employee.user.phone }}" class="email mt-2">{{ employee.user.email }}</a> {% endcomment %}
                    <a href="{% url 'customer:customer_appointment' service_id=service.pk employee_id=employee.pk %}" class="btn btn-primary w-100 position-relative" style="z-index: 3;">Take An Appointment</a>
                  </div>
                  <a href="{% url 'service_details' slug=request.resolver_match.kwargs.slug employee_id=employee.pk %}" class="stretched-link"></a>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <p>No Service Providers.</p>
          {% endif %}

          {% comment %}card{% endcomment %}
          {% comment %} <div class="col-4 d-flex justify-content-center my-3" style="width: 18rem;">
            <div class="card align-items-center" style="width: 18rem;">
              <img src="static/img/services/human1.jpg" class="card-img-top card-image" alt="..." />
              <div class="card-body">
                <h5 class="card-title">Mukesh Mahato</h5>
                <span class="service-provider-post">Plumber</span>
                <span>Experience:</span> <b>5 Years</b>
                <p class="contact mt-2 mb-0">9812345676</p>
                <p class="email mt-2">contact@mukesh.com.np</p>
                <a href="#" class="btn btn-primary w-100">Book</a>
              </div>
            </div>
          </div> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</section>

homeservice/templates/components/services_list.html
<section class="Services">
  <div class="container">
    <h2 style="text-align: center">Our Services</h2>
    <div class="mt-5">
      <div class="row gx-4 mt-3">
        {% if services %}
          {% for item in services %}
            <div class="col-md-6 col-lg-4 col-sm-12 mb-4">
              <div class="card text-center">
                <div class="card-header">{{ item.name }}</div>
                <div class="card-body card-image">
                  <img src="{{ item.image.url }}" class="rounded" alt="{{ item.name }}" />
                  <p class="card-text">{{ item.description|slice:':140' }}...</p>
                  {% if '/customer/' in request.path %}
                  <a href="/customer/service/{{ item.slug }}" class="btn btn-primary">Explore</a>
                  {% else %}
                  <a href="/service/{{ item.slug }}" class="btn btn-primary">Explore</a>
                  {% endif %} 
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>No services are available</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>